# Base de datos
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# SmallRye JWT - Verificación
mp.jwt.verify.issuer=https://archetype-auth.com
mp.jwt.verify.publickey.location=publicKey.pem

# SmallRye JWT - Firma (Generación)
smallrye.jwt.sign.key.location=privateKey.pem

# Excluir rutas públicas del filtro de seguridad
quarkus.http.auth.permission.public.paths=/api/health,/api/auth/*
quarkus.http.auth.permission.public.policy=permit
